[tool.ruff]
target-version = "py39"
line-length = 100

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
]
ignore = [
    "E501",
    "B008",
    "C901",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "E501",
    "F401",
    "F841",
    "B006",
    "E402",
    "E722",
    "UP006",
    "UP035",
]
"tools/*" = [
    "E402",
    "E741",
    "F841",
    "UP006",
    "UP035",
]
"data/*" = [
    "UP006",
    "UP035",
]
"__init__.py" = [
    "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["sush"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
